### ISSUE TITLE
Does this package support on Windows?

### ISSUE THREAD

**Issue by RikitoNoto** [ivirtex/lan_scanner#10]
Hi, ivirtex.
When I tried this package on Windows Application,
I occur the error like follow.
```
[ERROR:flutter/runtime/dart_isolate.cc(1098)] Unhandled exception:
FormatException: Unexpected extension byte (at offset 16)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1851:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#9      _StreamController._add (dart:async/stream_controller.dart:648:7)
#10     _StreamController.add (dart:async/stream_controller.dart:596:5)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#15     _StreamController._add (dart:async/stream_controller.dart:648:7)
#16     _StreamController.add (dart:async/stream_controller.dart:596:5)
#17     _Socket._onData (dart:io-patch/socket_patch.dart:2355:41)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#22     _StreamController._add (dart:async/stream_controller.dart:648:7)
#23     _StreamController.add (dart:async/stream_controller.dart:596:5)
#24     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1877:33)
#25     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1334:14)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

Doesn't this package support on Windows?

P.S. I love your applications. especially networkarch-flutter is my favorite.

**Comment by ivirtex** [comment]
Hi!

Thank you for opening this issue and for your PS message, it means a lot to me :)

It should work on Windows and I'm not really sure what happened. I will look into it as soon as I have more time.
